name: Lint Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Get list of changed Python files
      id: changed_files
      run: |
        git fetch origin ${{ github.base_ref }}
        CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} -- '*.py')
        echo "$FULL_PATH_FILES"

    - name: Run pylint linter on changed files
      if: success() && steps.changed_files.outputs.changed_files != ''
      run: |
        cd flask_starterkit
        pylint $CHANGED_FILES
